project_id = "navalhaos"

[functions.create-recurring-payment]
verify_jwt = true

[functions.issue-invoice]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false


[functions.sync-payment-status]
verify_jwt = true


[functions.get-payment-share-data]
verify_jwt = true
