project_id = "navalhaos"

[functions.create-recurring-payment]
verify_jwt = true

[functions.issue-invoice]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false


[functions.sync-payment-status]
verify_jwt = true


[functions.get-payment-share-data]
verify_jwt = true


[functions.cancel-payment]
verify_jwt = true


[functions.cancel-subscription]
verify_jwt = true


[functions.create-system-subscription]
verify_jwt = false


[functions.process-system-subscriptions]
verify_jwt = false


[functions.cancel-system-subscription]
verify_jwt = true
